### PR TITLE
Created logo, added to README

### PR DESCRIPTION
**Pull request by IsaccBarker**
While I would love to contribute to Kerla with code, I simply don't have the time currently. This project is really cool (and even if it is "just for fun"), I would still like to contribute in some way before I actually have time again.

This is not the greatest logo, as I was pressed for time while making it, but if you have any suggestions I would be happy to make a new one. That's only if you want a logo though (;

### CODE REVIEW

**Comment by IsaccBarker** [comment]
#34

**Comment by IsaccBarker** [comment]
Oh, and I figure this goes without saying, but the reason you cannot see the logo in the "browse file" window is because it uses a relative link (not unlike the screenshot image). You can navigate to my fork to see how it actually looks.

**Comment by nuta** [comment]
Adding a logo sounds neat but personally I'd avoid a complicated logo like this because a simple logo (like [Deno](https://github.com/denolib/high-res-deno-logo)) is easier to recognize it even when it's small.

Give me a time to think about the logo candidates (ideas like this PR is helpful to me and I really appreciate 😃)

**Comment by IsaccBarker** [comment]
Sounds good!

**Pull request closed without merging**
